# Generated by Django 5.2.11 on 2026-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='plan_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
