# Generated by Django 6.0 on 2026-02-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_badge_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_choice',
            field=models.CharField(default='dark', max_length=20),
        ),
    ]
