# Generated by Django 6.0 on 2026-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_avatar_customuser_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='study_mode',
            field=models.CharField(choices=[('Study', 'Study'), ('Quiz', 'Quiz'), ('Chat', 'Chat')], default='Study', max_length=20),
        ),
    ]
