# Generated by Django 6.0 on 2026-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_default_difficulty_customuser_study_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_study_goal',
            field=models.IntegerField(default=30, help_text='Daily study goal in minutes'),
        ),
    ]
