# Generated by Django 5.2.11 on 2026-02-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
